config/routes.rb
Rails.application.routes.draw do
  
  resources :line_items

  resources :inquirylists, only: [:show]

  root 'pages#home'

  get 'products' => 'products#index'

  get 'categories/:id/brands/:brand_id' => 'categories#show', as:"categories_in"
  get 'brands/:id/categories/:category_id' => 'brands#show', as:"brands_in"
  get 'categories/:id/:sub_id' => 'categories#showsub', as:"subcategory"
  
  devise_for :customers, :controllers => { registrations: 'registrations' }, :skip => [:sessions]

  as :customer do
    get 'login' => 'devise/sessions#new', :as => :new_customer_session
    post 'login' => 'devise/sessions#create', :as => :customer_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_customer_session
  end

  namespace :admin do
    get 'login' => 'sessions#new', :as => 'login'
    get "logout" => 'sessions#destroy', :as => "logout"
  end

  resources "products", only: [:show]
  resources "categories", only: [:show]
  resources "brands", only: [:show]

  get 'contact_us' => 'contacts#new', as:"contact"

  resources 'contacts', only: [:create]

  get :send_inquiry_mail, to: 'inquirylists#send_inquiry_mail', as: :send_inquiry_mail

  get 'about' => 'pages#about'

  namespace :admin do
    resources "informations"
  end

  namespace :admin do
    resources :products, :categories, :brands, :users, :customers
    resources "sessions", only: [:new, :create]
  end

  get "admin/categories/:id/sub/new" => 'admin/categories#newsub', :as => :new_admin_subcategory
  post "admin/categories/:id/sub/new" => 'admin/categories#createsub'
  get "admin/categories/:id/subs" => 'admin/categories#indexsub', :as => :admin_subcategories
  get "admin/categories/:id/subs/:sub_id" => 'admin/categories#showsub', :as => :admin_subcategory
  get "admin/categories/:id/subs/:sub_id/edit" => 'admin/categories#editsub', :as => :edit_admin_subcategory
  patch "admin/categories/:id/subs/:sub_id/edit" => 'admin/categories#updatesub'
  delete "admin/categories/:id/subs/:sub_id" => 'admin/categories#destroysub'

  delete "inquirylists/:id/destroy_all" => 'line_items#destroy_all'
end

app/models/brand.rb
class Brand < ActiveRecord::Base
	has_many :products

	validates_presence_of :name

	def self.search(query)
		where("name like ?", "%#{query}%")
	end
end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < Admin::ApplicationController
  before_filter :verify_logged_in
  def new
    @page_title = 'Add Brand'
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)
    if @brand.save
      flash[:notice] = 'New brand is created'
      redirect_to admin_brands_path
    else
      render 'new'
    end
  end

  def edit
    @page_title = "Edit Brand"
    @brand = Brand.find(params[:id])
  end

  def update
    @brand = Brand.find(params[:id])
    if @brand.update(brand_params)
      flash[:notice] = 'Brand has been edited'
      redirect_to admin_brands_path
    else
      flash[:alert] = 'Editing failed'
      render 'edit'
    end
  end

  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy
    flash[:notice] = 'Brand has been deleted'
    redirect_to admin_brands_path
  end

  def index
    @page_title = 'Manage Brands'
    @brands = Brand.all.order(:name)
    @categories = Category.all
  end

  def show
    @brand = Brand.find(params[:id])
    @products = @brand.products
  end

  private
  def brand_params
    params.require(:brand).permit(:name, :category_id)
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
	# this is custom method in application_controller
  # before_action :auth_customer

  def show
  	@categories = Category.all # for category sidebar
  	@brands = Brand.all # for brand sidebar

  	@brand = Brand.find(params[:id])
  	@products = @brand.products.paginate(:per_page => 9, :page => params[:page])
  	if params[:category_id].present?
  		@products = @products.where("category_id = ?", params[:category_id]).paginate(:per_page => 9, :page => params[:page])
  	# @products = Product.where("category_id = ? AND brand_id = ?", params[:category_id],params[:id]).paginate(:per_page => 9, :page => params[:page])
  	end
  end
end

app/helpers/admin/brands_helper.rb
module Admin::BrandsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/admin/brands/create.html.erb
<h1>Admin::Brands#create</h1>
<p>Find me in app/views/admin/brands/create.html.erb</p>

app/views/admin/brands/destroy.html.erb
<h1>Admin::Brands#destroy</h1>
<p>Find me in app/views/admin/brands/destroy.html.erb</p>

app/views/admin/brands/edit.html.erb
<script>
  $(function() {
    $('textarea#edit').editable({
      inlineMode: false
    })
  });
</script>

<div class="container middle-position-form">
	<h1 class="form-page-header"><%= @page_title %></h1>
	<%= render 'partials/brandForm' %>
</div>

app/views/admin/brands/index.html.erb
<h2 class="page-header"><%= @page_title %> <%= link_to "Create New", new_admin_brand_path, class:'btn btn-primary pull-right'%></h2>
<% if @brands.exists? %>
	<table class="table table-striped">
	<tr>
	  <th>Brand Title</th>
	  <th>Product Quantity</th>
	  <th>Actions</th>
	</tr>
	<% @brands.each do |brand| %>
	<tr>
	  <td><%= brand.name %></td>
	  <td><%= link_to brand.products.count, admin_brand_path(brand), class:'product-quantity' %></td>
	  <td><%= link_to "Edit", edit_admin_brand_path(brand), class:'btn btn-primary' %> <%= link_to "Delete", admin_brand_path(brand), class:'btn btn-danger', method: :delete, data: {confirm: 'Are you sure'} %></td>
	</tr>
	<% end %>
	</table>
<% else %>
	<p>There are no brands.</p>
<% end %>

app/views/admin/brands/new.html.erb
<script>
  $(function() {
    $('textarea#edit').editable({
      inlineMode: false
    })
  });
</script>

<div class="container middle-position-form">
	<h1 class="form-page-header"><%= @page_title %></h1>
	<%= render 'partials/brandForm' %>
</div>

app/views/admin/brands/show.html.erb
<h2 class="page-header">Manage Products In : <%= @brand.name %> <%= link_to "Create New", new_admin_product_path, class:'btn btn-primary pull-right'%></h2>
<% if @products.exists? %>
	<table class="table table-striped">
	<tr>
	  <th>Product Title</th>
	  <th>Product Image</th>
	  <th>Brand</th>
	  <th>Category</th>
	  <th>Product Description</th>
	  <th>Actions</th>
	</tr>
	<% @products.each do |product| %>
	<tr class="admin-productForm">
	  <td><%= product.title %></td>
	  <td class="product-img-preview"><%= image_tag(product.image) %></td>
	  <td><%= product.brand.name%></td>
	  <td><%= product.brand.name%></td>
	  <td class="admin-product-description" ><%= simple_format(product.description) %></td>
	  <td><%= link_to "Edit", edit_admin_product_path(product), class:'btn btn-primary' %> <%= link_to "Delete", admin_product_path(product), class:'btn btn-danger', method: :delete, data: {confirm: 'Are you sure'} %></td>
	</tr>
	<% end %>
	</table>
<% else %>
	<p>There are no products in this brand yet.</p>
<% end %>

app/views/admin/brands/update.html.erb
<h1>Admin::Brands#update</h1>
<p>Find me in app/views/admin/brands/update.html.erb</p>