config/routes.rb
Rails.application.routes.draw do
  
  resources :line_items

  resources :inquirylists, only: [:show]

  root 'pages#home'

  get 'products' => 'products#index'

  get 'categories/:id/brands/:brand_id' => 'categories#show', as:"categories_in"
  get 'brands/:id/categories/:category_id' => 'brands#show', as:"brands_in"
  get 'categories/:id/:sub_id' => 'categories#showsub', as:"subcategory"
  
  devise_for :customers, :controllers => { registrations: 'registrations' }, :skip => [:sessions]

  as :customer do
    get 'login' => 'devise/sessions#new', :as => :new_customer_session
    post 'login' => 'devise/sessions#create', :as => :customer_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_customer_session
  end

  namespace :admin do
    get 'login' => 'sessions#new', :as => 'login'
    get "logout" => 'sessions#destroy', :as => "logout"
  end

  resources "products", only: [:show]
  resources "categories", only: [:show]
  resources "brands", only: [:show]

  get 'contact_us' => 'contacts#new', as:"contact"

  resources 'contacts', only: [:create]

  get :send_inquiry_mail, to: 'inquirylists#send_inquiry_mail', as: :send_inquiry_mail

  get 'about' => 'pages#about'

  namespace :admin do
    resources "informations"
  end

  namespace :admin do
    resources :products, :categories, :brands, :users, :customers
    resources "sessions", only: [:new, :create]
  end

  get "admin/categories/:id/sub/new" => 'admin/categories#newsub', :as => :new_admin_subcategory
  post "admin/categories/:id/sub/new" => 'admin/categories#createsub'
  get "admin/categories/:id/subs" => 'admin/categories#indexsub', :as => :admin_subcategories
  get "admin/categories/:id/subs/:sub_id" => 'admin/categories#showsub', :as => :admin_subcategory
  get "admin/categories/:id/subs/:sub_id/edit" => 'admin/categories#editsub', :as => :edit_admin_subcategory
  patch "admin/categories/:id/subs/:sub_id/edit" => 'admin/categories#updatesub'
  delete "admin/categories/:id/subs/:sub_id" => 'admin/categories#destroysub'

  delete "inquirylists/:id/destroy_all" => 'line_items#destroy_all'
end

app/models/brand.rb
class Brand < ActiveRecord::Base
	has_many :products

	validates_presence_of :name

	def self.search(query)
		where("name like ?", "%#{query}%")
	end
end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < Admin::ApplicationController
  before_filter :verify_logged_in
  def new
    @page_title = 'Add Brand'
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)
    if @brand.save
      flash[:notice] = 'New brand is created'
      redirect_to admin_brands_path
    else
      render 'new'
    end
  end

  def edit
    @page_title = "Edit Brand"
    @brand = Brand.find(params[:id])
  end

  def update
    @brand = Brand.find(params[:id])
    if @brand.update(brand_params)
      flash[:notice] = 'Brand has been edited'
      redirect_to admin_brands_path
    else
      flash[:alert] = 'Editing failed'
      render 'edit'
    end
  end

  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy
    flash[:notice] = 'Brand has been deleted'
    redirect_to admin_brands_path
  end

  def index
    @page_title = 'Manage Brands'
    @brands = Brand.all.order(:name)
    @categories = Category.all
  end

  def show
    @brand = Brand.find(params[:id])
    @products = @brand.products
  end

  private
  def brand_params
    params.require(:brand).permit(:name, :category_id)
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
	# this is custom method in application_controller
  # before_action :auth_customer

  def show
  	@categories = Category.all # for category sidebar
  	@brands = Brand.all # for brand sidebar

  	@brand = Brand.find(params[:id])
  	@products = @brand.products.paginate(:per_page => 9, :page => params[:page])
  	if params[:category_id].present?
  		@products = @products.where("category_id = ?", params[:category_id]).paginate(:per_page => 9, :page => params[:page])
  	# @products = Product.where("category_id = ? AND brand_id = ?", params[:category_id],params[:id]).paginate(:per_page => 9, :page => params[:page])
  	end
  end
end

app/helpers/admin/brands_helper.rb
module Admin::BrandsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/show.html.erb
<div class="row">
  <%= render 'partials/sidebar' %> 
	<div class="col-lg-9 col-md-9 col-xs-9 category-all-product">
		<h2 class="category-name-title"><%= @brand.name %></h2>
		<div class="topic-underline"></div>

    <ul class="custom-nav custom-nav-pills">
        <% if @categories.exists? %>
          <li class="<%= 'active' if current_page?(brand_path) %>"><%= link_to "All", brand_path(@brand) %></li><span class="tab-divider"> | </span>
          <% @categories.each do |category| %>
            <% @product_category = Product.where("brand_id = ? AND category_id = ?", params[:id], category.id) %>
            <% if @product_category.exists? %>
              <li class="<%= 'active' if params[:category_id] == category.id.to_s %>">
                <%= link_to(brands_in_path(params[:id],category.id)) do %>
                <span><%= category.name %></span><span class="badge"><%= @product_category.count.to_s %></span>
                <% end %>
              </li>
              <span class="tab-divider"> | </span>
            <% end %>
          <% end %>
        <% else %>
          <p>There are no categories of this brand.</p>
        <% end %>
    </ul>

	  <% if @products.exists? %>
	  	<%= render 'partials/showPageProductRow' %>
	  <% else %>
	    <p>No products for this brand yet.</p>
	  <% end %>

    <% if !customer_signed_in? %>
        <%= link_to 'Log in', new_customer_session_path, class:"btn btn-warning" %> or <%= link_to 'Sign up', new_customer_registration_path, class:"btn btn-info" %><span style="color:black;"> to see product details and take inquiries.</span>
      <% end %>
	</div>
</div>