config/routes.rb
Rails.application.routes.draw do
  
  resources :line_items

  resources :inquirylists, only: [:show]

  root 'pages#home'

  get 'products' => 'products#index'

  get 'categories/:id/brands/:brand_id' => 'categories#show', as:"categories_in"
  get 'brands/:id/categories/:category_id' => 'brands#show', as:"brands_in"
  get 'categories/:id/:sub_id' => 'categories#showsub', as:"subcategory"
  
  devise_for :customers, :controllers => { registrations: 'registrations' }, :skip => [:sessions]

  as :customer do
    get 'login' => 'devise/sessions#new', :as => :new_customer_session
    post 'login' => 'devise/sessions#create', :as => :customer_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_customer_session
  end

  namespace :admin do
    get 'login' => 'sessions#new', :as => 'login'
    get "logout" => 'sessions#destroy', :as => "logout"
  end

  resources "products", only: [:show]
  resources "categories", only: [:show]
  resources "brands", only: [:show]

  get 'contact_us' => 'contacts#new', as:"contact"

  resources 'contacts', only: [:create]

  get :send_inquiry_mail, to: 'inquirylists#send_inquiry_mail', as: :send_inquiry_mail

  get 'about' => 'pages#about'

  namespace :admin do
    resources "informations"
  end

  namespace :admin do
    resources :products, :categories, :brands, :users, :customers
    resources "sessions", only: [:new, :create]
  end

  get "admin/categories/:id/sub/new" => 'admin/categories#newsub', :as => :new_admin_subcategory
  post "admin/categories/:id/sub/new" => 'admin/categories#createsub'
  get "admin/categories/:id/subs" => 'admin/categories#indexsub', :as => :admin_subcategories
  get "admin/categories/:id/subs/:sub_id" => 'admin/categories#showsub', :as => :admin_subcategory
  get "admin/categories/:id/subs/:sub_id/edit" => 'admin/categories#editsub', :as => :edit_admin_subcategory
  patch "admin/categories/:id/subs/:sub_id/edit" => 'admin/categories#updatesub'
  delete "admin/categories/:id/subs/:sub_id" => 'admin/categories#destroysub'

  delete "inquirylists/:id/destroy_all" => 'line_items#destroy_all'
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
	has_many :subcategories

	validates_presence_of :name

	def self.search(query)
		where("name like ?", "%#{query}%")
	end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_filter :verify_logged_in
  def new
    @page_title = "Add New Category"
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)    
    if @category.save
      flash[:notice] = 'Category"' + @category.name + '" Created'
      redirect_to admin_categories_path
    else
      render 'new'
    end
  end

  def edit
    @page_title = 'Edit Category'
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = 'Category "' + @category.name + '" Updated'
      redirect_to admin_categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      flash[:notice] = 'Category "' + @category.name + '" Deleted'
      redirect_to admin_categories_path
    else
      flash[:notice] = 'Category "' + @category.name + '" is not Deleted'
      redirect_to admin_categories_path
    end
  end

  def index
    if params[:search]
      @page_title = "Search for: " + params[:search]
      @categories = Category.search(params[:search]).all.order(:name).paginate(:per_page => 10, :page => params[:page])
    else      
      @categories = Category.all.order(:name).paginate(:per_page => 10, :page => params[:page])
    end
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products
  end

  def newsub
    @category = Category.find(params[:id])
    @page_title = "Add New Subcategory of " + @category.name
    @subcategory = Subcategory.new    
  end

  def createsub
    @category = Category.find(params[:id])
    @subcategory = Subcategory.new(subcategory_params)
    if @subcategory.save
      flash[:notice] = 'Subcategory"' + @subcategory.name + '"is created of ' + @category.name
      redirect_to admin_categories_path
    else
      render 'new'
    end
  end

  def indexsub
    @category = Category.find(params[:id])
    @subcategories = @category.subcategories
  end

  def showsub
    @subcategory = Subcategory.find(params[:sub_id])
    @products = @subcategory.products
  end

  def editsub
    @category = Category.find(params[:id])
    @subcategory = Subcategory.find(params[:sub_id])
  end

  def updatesub
    @subcategory = Subcategory.find(params[:sub_id])
    if @subcategory.update(subcategory_params)
      flash[:notice] = 'Subcategory "' + @subcategory.name + '" Updated'
      redirect_to admin_subcategories_path
    else
      render 'edit'
    end
  end

  def destroysub
    @subcategory = Subcategory.find(params[:sub_id])
    if @subcategory.destroy
      flash[:notice] = "subcategory destroyed."
      redirect_to admin_subcategories_path
    end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
  def subcategory_params
    params.require(:subcategory).permit(:name, :category_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # this is custom method in application_controller
  # before_action :auth_customer

  def show
  	@categories = Category.all # for category sidebar
  	@brands = Brand.all # for brand sidebar

  	@category = Category.find(params[:id])
  	@products = @category.products.paginate(:per_page => 9, :page => params[:page])
  	if params[:brand_id].present?
  		@products = @products.where("brand_id = ?", params[:brand_id]).paginate(:per_page => 9, :page => params[:page])
  	# @products = Product.where("category_id = ? AND brand_id = ?", params[:id],params[:brand_id]).paginate(:per_page => 9, :page => params[:page])
  	end
  end

  def showsub
    @categories = Category.all # for category sidebar
    @brands = Brand.all # for brand sidebar
    @category = Category.find(params[:id])
    @subcategory = @category.subcategories.find_by_id(params[:sub_id])
    @products = @subcategory.products.paginate(:per_page => 9, :page => params[:page])
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/show.html.erb
<div class="row">
  <%= render 'partials/sidebar' %> 
	<div class="col-lg-9 col-md-9 col-sm-12 category-all-product">
		<h2 class="category-name-title"><%= @category.name %></h2>
		<div class="topic-underline"></div>

    <ul class="custom-nav custom-nav-pills">
      <% comment do %>
        <% if @brands.exists? %>
          <li class="<%= 'active' if current_page?(category_path) %>"><%= link_to "All", category_path(@category) %></li><span class="tab-divider"> | </span>
          <% @brands.each do |brand| %>
            <% @product_brand = Product.where("category_id = ? AND brand_id = ?", params[:id],brand.id) %>
            <% if @product_brand.exists? %>
              <li class="<%= 'active' if params[:brand_id] == brand.id.to_s %>">
                <%= link_to(categories_in_path(params[:id],brand.id)) do %>
                <span><%= brand.name %></span><span class="badge"><%= @product_brand.count.to_s %></span>
                <% end %>
              </li>
              <span class="tab-divider"> | </span>
            <% end %>
          <% end %>
        <% else %>
          <p>There are no brands in this category.</p>
        <% end %>
      <% end %>
    </ul>

	  <% if @products.exists? %>     
      <%= form_tag(products_path, :method => "get", id:"sidebar-search-form-group", class:"search-form") do %>
        <div class="col-lg-8 col-md-8 col-xs-8 sidebar-col">
          <div class="form-group" id="sidebar-search-form" style="display:inline-block;">
          <h3>請輸入密碼：</h3>
          <%= text_field_tag :search, params[:search], class:'form-control' %>
          </div>
        </div>
      <% end %>
      <%#= render 'partials/showPageProductRow' %>
	  <% else %>
	    <p>No products in this category yet.</p>
	  <% end %>

    <% comment do %>
    <% if !customer_signed_in? %>
        <%= link_to 'Log in', new_customer_session_path, class:"btn btn-warning" %> or <%= link_to 'Sign up', new_customer_registration_path, class:"btn btn-info" %><span style="color:black;"> to see product details and take inquiries.</span>
      <% end %>
    <% end %>
	</div>

</div>

app/views/categories/showsub.html.erb
<div class="row">
  <%= render 'partials/sidebar' %> 
	<div class="col-lg-9 col-md-9 col-sm-12 category-all-product">
		<h2 class="category-name-title"><%= @subcategory.name %></h2>
		<div class="topic-underline"></div>
    <% comment do %>
    <ul class="custom-nav custom-nav-pills">
        <% if @brands.exists? %>
          <li class="<%= 'active' if current_page?(category_path) %>"><%= link_to "All", subcategory_path(params[:id],params[:sub_id]) %></li><span class="tab-divider"> | </span>
          <% @brands.each do |brand| %>
            <% @product_brand = Product.where("category_id = ? AND brand_id = ?", params[:id],brand.id) %>
            <% if @product_brand.exists? %>
              <li class="<%= 'active' if params[:brand_id] == brand.id.to_s %>">
                <%= link_to(subcategories_in_path(params[:id],brand.id)) do %>
                <span><%= brand.name %></span><span class="badge"><%= @product_brand.count.to_s %></span>
                <% end %>
              </li>
              <span class="tab-divider"> | </span>
            <% end %>
          <% end %>
        <% else %>
          <p>There are no brands in this category.</p>
        <% end %>
    </ul>
    <% end %>

	  <% if @products.exists? %>
	  	<%= render 'partials/showPageProductRow' %>
	  <% else %>
	    <p>No products in this category yet.</p>
	  <% end %>

    <% if !customer_signed_in? %>
        <%= link_to 'Log in', new_customer_session_path, class:"btn btn-warning" %> or <%= link_to 'Sign up', new_customer_registration_path, class:"btn btn-info" %><span style="color:black;"> to see product details and take inquiries.</span>
      <% end %>
	</div>

</div>