config/routes.rb
Rails.application.routes.draw do
  
  resources :line_items

  resources :inquirylists, only: [:show]

  root 'pages#home'

  get 'products' => 'products#index'

  get 'categories/:id/brands/:brand_id' => 'categories#show', as:"categories_in"
  get 'brands/:id/categories/:category_id' => 'brands#show', as:"brands_in"
  get 'categories/:id/:sub_id' => 'categories#showsub', as:"subcategory"
  
  devise_for :customers, :controllers => { registrations: 'registrations' }, :skip => [:sessions]

  as :customer do
    get 'login' => 'devise/sessions#new', :as => :new_customer_session
    post 'login' => 'devise/sessions#create', :as => :customer_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_customer_session
  end

  namespace :admin do
    get 'login' => 'sessions#new', :as => 'login'
    get "logout" => 'sessions#destroy', :as => "logout"
  end

  resources "products", only: [:show]
  resources "categories", only: [:show]
  resources "brands", only: [:show]

  get 'contact_us' => 'contacts#new', as:"contact"

  resources 'contacts', only: [:create]

  get :send_inquiry_mail, to: 'inquirylists#send_inquiry_mail', as: :send_inquiry_mail

  get 'about' => 'pages#about'

  namespace :admin do
    resources "informations"
  end

  namespace :admin do
    resources :products, :categories, :brands, :users, :customers
    resources "sessions", only: [:new, :create]
  end

  get "admin/categories/:id/sub/new" => 'admin/categories#newsub', :as => :new_admin_subcategory
  post "admin/categories/:id/sub/new" => 'admin/categories#createsub'
  get "admin/categories/:id/subs" => 'admin/categories#indexsub', :as => :admin_subcategories
  get "admin/categories/:id/subs/:sub_id" => 'admin/categories#showsub', :as => :admin_subcategory
  get "admin/categories/:id/subs/:sub_id/edit" => 'admin/categories#editsub', :as => :edit_admin_subcategory
  patch "admin/categories/:id/subs/:sub_id/edit" => 'admin/categories#updatesub'
  delete "admin/categories/:id/subs/:sub_id" => 'admin/categories#destroysub'

  delete "inquirylists/:id/destroy_all" => 'line_items#destroy_all'
end

app/views/partials/admin/_categoryForm.html.erb
<%= form_for [:admin, @category] do |f| %>
	<!-- Check for errors -->
	<% if @category.errors.any? %>
	    <% @category.errors.full_messages.each do |msg| %>
	    	<!-- Show errors -->
	      	<div class="alert alert-danger"><%= msg %></div>
	    <% end %>
  	<% end %>
  	
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class:'form-control' %>
	</div>
	<br />
	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", admin_categories_path, class:'btn btn-default' %>

<% end %>

app/views/partials/admin/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%= link_to 'H.C.H Machinery Works', root_path, class:'navbar-brand' %>
          <li class="<%= 'active' if current_page?(admin_categories_path) %>"><%= link_to "Category", admin_categories_path %></li>
          <li class="<%= 'active' if current_page?(admin_brands_path) %>"><%= link_to "Brand", admin_brands_path %></li>
          <li class="<%= 'active' if current_page?(admin_products_path) %>"><%= link_to "Product", admin_products_path %></li>
          <li class="<%= 'active' if current_page?(admin_informations_path) %>"><%= link_to "Info", admin_informations_path %></li>

          <li class="dropdown <%= 'active' if current_page?(admin_customers_path) || current_page?(admin_users_path) %>">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Users<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Customer", admin_customers_path %></li>
              <li><%= link_to "AdminUser", admin_users_path %></li>
            </ul>
          </li>

          <% if current_user %>
            <li class="dropdown pull-right">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.name.upcase %><span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Log out", admin_logout_path %></li>
              </ul>
            </li>
          <% else %>
            <li class="pull-right"><%= link_to "Sign in", admin_login_path %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/admin/_productForm.html.erb
<%= simple_form_for [:admin, @product] do |f| %>
	<!-- Check for errors -->
	<% if @product.errors.any? %>
	    <% @product.errors.full_messages.each do |msg| %>
	    	<!-- Show errors -->
	      	<div class="alert alert-danger"><%= msg %></div>
	    <% end %>
  	<% end %>
  	
	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title, class:'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :category %>
		<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class:'form-control' %>
	</div>

	<div class="form-group">
		<%= f.input :subcategory_id, collection: Category.all, as: :grouped_select, group_method: :subcategories, prompt: "Select One" %>
	</div>

	<div class="form-group">
		<%= f.label :brand %>
		<%= f.select :brand_id, Brand.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class:'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :image %>
		<%= f.text_field :image, class:'form-control' %>
	</div>

	<div class="product-img-preview">
		<%= image_tag(@product.image) %>
	</div>

	<div class="form-group">
		<%= f.label :tags %>
		<%= f.text_field :tags, class:'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :model_name, 'Model' %>
		<%= f.text_field :model_name, class:'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :item_number, 'Item Number' %>
		<%= f.text_field :item_number, class:'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :part_number, 'Part Number' %>
		<p>Please use comma to separate each part number. Ex: 123-123,456-456,789-789</p>
		<%= f.text_field :part_number, class:'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :diameter, 'Diameter' %>
		<%= f.text_field :diameter, class:'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :size, 'Size' %>
		<%= f.text_field :size, class:'form-control' %>
	</div>

	<div class="form-group product-description-form">
		<%= f.label :description %><p>Each line less than 22 words suggested.</p>
		<%= f.text_area :description, class:'form-control', id:'edit' %>
	</div>
	<br />
	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", admin_products_path, class:'btn btn-default' %>

<% end %>

app/views/partials/admin/_productInfo.html.erb
<% comment do %>
	<% if !product.model_name.blank? %>
		MODEL: <%= product.model_name %><br/>
	<% end %>
<% end %>
<% if !product.item_number.blank? %>
	ITEM No.: <%= product.item_number %><br/>
<% end %>
<% if !product.part_number.blank? %>
	PART No.: <%= product.part_number %><br/>
<% end %>
<% if !product.diameter.blank? %>
	DIAMETER(mm): <%= product.diameter %><br/>
<% end %>
<% if !product.size.blank? %>
	SIZE: <%= product.size %><br/>
<% end %>